openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://localhost:8080/
tags:
  - name: Booking
  - name: Room
  - name: Type
paths:
  /booking:
    get:
      tags:
        - Booking
      summary: Get list of bookings
      description: How to get booking List
      parameters:
        - name: page
          in: query
          schema: 
            type: integer
            example: 0
          required: true
        - name: page_size
          in: query
          schema: 
            type: integer
            example: 10
          required: true  
      responses:
        200:
          description: Booking list
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref : '#/components/schemas/booking'
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
    post:
      tags:
        - Booking
      summary: Make reservation
      description: How to make a reservation
      requestBody:
        content:
          application/json:
            schema: 
              type: array
              items: 
                $ref: '#/components/schemas/addBooking'
        required: true
      responses:
        200:
          description: Booking made 
          content:
            text/plain:
              example: Booking made successfully
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
  /booking/{id}:
    get: 
      tags:
        - Booking
      summary: Get details of a booking
      description: Get informations of the booking having the entered id
      parameters:
        - name: id 
          in: path
          schema: 
            type: integer
            example: 1
          required: true
      responses:
        200:
          description: Informations of the specified booking
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/booking'
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
    put:
      tags:
        - Booking
      summary: Modify informations of the booking having the entered id
      description: |
          Possible changes/updates on: 
          * client's phone_number:
          * room type
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            example: 1
          required: true
      requestBody:
        description: informations to be changed 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/room'
            examples:
              UpdatePhoneNumber:
                description: change/update client's phone number
                value:
                  newContact: "+261421412412"
              UpdateRoomType: 
                description: change/update room's type
                value: 
                  newType: Family
        required: true
      responses:
        200:
          description: Informations updated 
          content:
            text/plain:
              example: Informations updated successfully
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
    
  /rooms:
    get:
      tags:
        - Room
      summary: Get list of rooms
      description: How to get the list of the hotel's rooms
      parameters:
        - name: page
          in: query
          schema: 
            type: integer
            example: 1
          required: true
        - name: page_size
          in: query
          schema:
            type: integer
            example: 10
          required: true
      responses:
        200:
          description: List of the hotel's rooms
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/room'
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
    post:
      tags:
        - Room
      summary: Add new room
      description: How to add a new room to the list
      requestBody:
        content:
          application/json:
            schema: 
              type: array
              items:
                $ref: '#/components/schemas/addRoom'
        required: true
      responses:
        200:
          description: New room added to the list
          content:
            text/plain:
              example: Room successfully added to the list 
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
  /rooms/{id}:
    get: 
      tags:
        - Room
      summary: Get info a room
      description: Get informations of the room having the entered id
      parameters:
        - name: id 
          in: path
          schema: 
            type: integer
            example: 1
          required: true
      responses:
        200:
          description: Informations of a specified room
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/room'
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
    put:
      tags:
        - Room
      summary: Modify informations of the room having the entered id
      description: |
          Possible changes/updates on: 
          * room's description
          *room's type
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            example: 1
          required: true
      requestBody:
        description: informations to be changed 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/room'
            examples:
              UpdateDescription:
                description: change/update room's description
                value:
                  newDescription: George Washington's room
              UpdateType: 
                description: change/update room's type
                value: 
                  newType: Family
        required: true
      responses:
        200:
          description: Informations updated 
          content:
            text/plain:
              example: Informations updated successfully
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
  /rooms/{available}:
    get: 
      tags:
        - Room
      summary: Get list of rooms according to their availability
      description: How to filter rooms by their availability
      parameters:
        - name: available
          in: path
          schema: 
            type: boolean
            example: true
          required: true
      responses:
        200:
          description: List of rooms filtered by their availability
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/room'
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
  /rooms/{type}:
    get:  
      tags:
        - Room
      summary: Get list of rooms according to their type 
      description: How to filter rooms by their type
      parameters:
        - name: type
          in: path
          schema: 
            type: string
            example: double
          required: true
      responses:
        200:
          description: List of rooms filtered by their type
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/room'
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
  /types:
    get:
      tags:
        - Type
      summary: Get rooms type
      description: How to get the rooms type
      parameters:
        - name: page
          in: query
          schema: 
            type: integer
            example: 1
          required: true
        - name: page_size
          in: query
          schema: 
            type: integer
            example: 5
          required: true
      responses:
        200:
          description: List of room types
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/type'
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
    post:   
      tags:
        - Type
      summary: Add new room type
      description: How to add new room type
      requestBody:
        content:
          application/json:
            schema: 
              type: array
              items:
                $ref: '#/components/schemas/addType'
        required: true
      responses:
        200:
          description: Types successfully added 
          content:
            text/plain:
              example: Types successfully added
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
  /types/{id}:
    get: 
      tags:
        - Type
      summary: Get room type details
      description: Get details on the room type having the entered id
      parameters:
        - name: id
          in: path
          schema: 
            type: integer
            example: 1
          required: true
      responses:
        200:
          description: Details about a room type
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/type'
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
    put: 
      tags:
        - Type
      summary: Modify room type details
      description: |
        Possible changes/updates on: 
          * type's name
          * type's description
          * type's price 
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            example: 1
          required: true
      requestBody:
        description: informations to be changed 
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/type'
            examples:
              UpdadeName: 
                description: change/update type's name
                value: 
                  new_name: Suit
              UpdateDescription:
                description: change/update type's description
                value:
                  new_description: Obama's Suit
              UpdatePrice: 
                description: change/update type's price
                value:
                  new_price: 250.000 Ar
        required: true
      responses:
        200:
          description: Informations updated
          content:
            text/plain:
              example: Informations updated
        400:
          description: Bad request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/badrequest'
components:
  schemas:
    badrequest:
      description: Bad request exception
      type: object
      properties:
        type: 
          type: string
          example: BadRequestException
        message:
          type: string
          example: Bad request
    addBooking: 
      description: description of a new booking
      type: object
      properties:
        client: 
            type: string
            example: Carl Johnson
        phone_number: 
            type: string
            example: "+261302112412"
        booking_date:
            type: string
            format: date
        room_type: 
            type: string
            example: double
    booking:
      description: description of a booking
      allOf:
        - $ref: '#/components/schemas/addBooking'
      type: object
      properties:
        id: 
          type: integer
          example: 1
    addRoom:
      description: description of a new room
      type: object
      properties:
        description: 
          type: string
          example: lorem ipsum
        type:
          type: string
          example: double
    room: 
      description: description of a room
      type: object
      properties:
        room_number:
          type: number
          example: 1
        description: 
          type: string
          example: lorem ipsum
        available: 
          type: boolean
        type:
          $ref: '#/components/schemas/type'
    addType:
      description: add a room type
      type: object
      properties:
        name: 
          type: string
          example: double
        description: 
          type: string
          example: 1 lit pour 2 personnes
        price: 
          type: string
          example: "100.000 Ar"
    type:
      description: rooms type
      allOf:
        - $ref: '#/components/schemas/addType'
      type: object
      properties:
        id: 
          type: integer
          example: 1